[functions.generate-embedding]
enabled = true
verify_jwt = false
import_map = "./functions/generate-embedding/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-embedding/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-embedding/*.html" ]

[functions.generate-summary]
enabled = true
verify_jwt = false
import_map = "./functions/generate-summary/deno.json"
entrypoint = "./functions/generate-summary/index.ts"
